class AddCommentsAndCustomsToHabitacions < ActiveRecord::Migration[5.0]
  def change
		add_column :habitacions, :demo_quitar_azulejo_comment, :string
		add_column :habitacions, :demo_quitar_baldosa_comment, :string
		add_column :habitacions, :demo_quitar_falso_techo_comment, :string
		add_column :habitacions, :demo_quitar_tabique_comment, :string
		add_column :habitacions, :demo_quitar_inodoro_comment, :string
		add_column :habitacions, :demo_quitar_bidet_comment, :string
		add_column :habitacions, :demo_quitar_plato_ducha_comment, :string
		add_column :habitacions, :demo_quitar_mampara_comment, :string
		add_column :habitacions, :demo_quitar_mueble_bano_comment, :string
		add_column :habitacions, :demo_quitar_banera_comment, :string
		add_column :habitacions, :demo_quitar_mobi_cocina_comment, :string
		add_column :habitacions, :demo_retir_electrodomesticos_comment, :string
		add_column :habitacions, :demo_friso_madera_comment, :string
		add_column :habitacions, :demo_quitar_mueble_comment, :string
		add_column :habitacions, :tub_termo_electrico_comment, :string
		add_column :habitacions, :tub_radiador_comment, :string
		add_column :habitacions, :tub_lavabo_comment, :string
		add_column :habitacions, :tub_ducha_banera_comment, :string
		add_column :habitacions, :tub_bidet_comment, :string
		add_column :habitacions, :tub_inodoro_comment, :string
		add_column :habitacions, :tub_colum_hidromasaje_comment, :string
		add_column :habitacions, :tub_lavabo_doble_comment, :string
		add_column :habitacions, :tub_jacuzzy_comment, :string
		add_column :habitacions, :tub_sauna_comment, :string
		add_column :habitacions, :tub_ducha_empotrada_comment, :string
		add_column :habitacions, :tub_toallero_comment, :string
		add_column :habitacions, :tub_reubicar_contador_comment, :string
		add_column :habitacions, :tub_lavadora_comment, :string
		add_column :habitacions, :tub_reubicar_inodoro_comment, :string
		add_column :habitacions, :tub_tipo_comment, :string
		add_column :habitacions, :tub_caldera_comment, :string
		add_column :habitacions, :tub_fregadero_comment, :string
		add_column :habitacions, :tub_lavavajillas_comment, :string
		add_column :habitacions, :tub_secadora_comment, :string
		add_column :habitacions, :elec_pto_luz_techo_comment, :string
		add_column :habitacions, :elec_pto_luz_pared_comment, :string
		add_column :habitacions, :elec_interr_simple_comment, :string
		add_column :habitacions, :elec_interr_doble_comment, :string
		add_column :habitacions, :elec_interr_triple_comment, :string
		add_column :habitacions, :elec_enchu_simple_comment, :string
		add_column :habitacions, :elec_enchu_doble_comment, :string
		add_column :habitacions, :elec_enchu_triple_comment, :string
		add_column :habitacions, :elec_reubicar_caja_luz_comment, :string
		add_column :habitacions, :elec_toma_lavadora_comment, :string
		add_column :habitacions, :elec_toma_ventilador_extractor_comment, :string
		add_column :habitacions, :elec_toma_horno_vitroceramica_comment, :string
		add_column :habitacions, :elec_toma_microondas_comment, :string
		add_column :habitacions, :elec_toma_frigorifico_comment, :string
		add_column :habitacions, :elec_toma_lavavajillas_comment, :string
		add_column :habitacions, :elec_toma_secadora_comment, :string
		add_column :habitacions, :elec_toma_telefono_comment, :string
		add_column :habitacions, :alb_azulejo_comment, :string
		add_column :habitacions, :alb_tipo_azulejo_comment, :string
		add_column :habitacions, :alb_baldosa_comment, :string
		add_column :habitacions, :alb_tipo_baldosa_comment, :string
		add_column :habitacions, :alb_techo_pladur_comment, :string
		add_column :habitacions, :alb_tabique_ladriyeso_comment, :string
		add_column :habitacions, :alb_tabique_pladur_comment, :string
		add_column :habitacions, :alb_tabique_fabrica_comment, :string
		add_column :habitacions, :alb_tabique_paves_comment, :string
		add_column :habitacions, :alb_nivelacion_pared_comment, :string
		add_column :habitacions, :mont_sani_mampara_comment, :string
		add_column :habitacions, :mont_sani_mueble_bano_comment, :string
		add_column :habitacions, :mont_sani_banera_comment, :string
		add_column :habitacions, :mont_sani_plato_ducha_comment, :string
		add_column :habitacions, :mont_sani_bidet_comment, :string
		add_column :habitacions, :mont_sani_inodoro_normal_comment, :string
		add_column :habitacions, :mont_sani_inodoro_suspendido_comment, :string
		add_column :habitacions, :mont_sani_inodoro_encastrado_comment, :string
		add_column :habitacions, :mont_sani_grifo_ducha_comment, :string
		add_column :habitacions, :mont_sani_grifo_banera_comment, :string
		add_column :habitacions, :mont_sani_acceso_atornillado_comment, :string
		add_column :habitacions, :mont_sani_colum_hidromasaje_comment, :string
		add_column :habitacions, :mont_sani_cabina_ducha_comment, :string
		add_column :habitacions, :mont_sani_plato_ducha_obra_comment, :string
		add_column :habitacions, :mont_sani_lavabo_pedestal_comment, :string
		add_column :habitacions, :mont_electro_mueble_alto_cocina_comment, :string
		add_column :habitacions, :mont_electro_mueble_bajo_cocina_comment, :string
		add_column :habitacions, :mont_electro_horno_electrico_comment, :string
		add_column :habitacions, :mont_electro_placa_vitro_comment, :string
		add_column :habitacions, :mont_electro_placa_electrica_comment, :string
		add_column :habitacions, :mont_electro_lavadora_comment, :string
		add_column :habitacions, :mont_electro_frigorifico_comment, :string
		add_column :habitacions, :mont_electro_lavavajillas_comment, :string
		add_column :habitacions, :mont_electro_microondas_comment, :string
		add_column :habitacions, :mont_electro_secadora_comment, :string
		add_column :habitacions, :mont_fregadero_comment, :string
		add_column :habitacions, :mont_grifo_fregadero_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_a_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_b_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_c_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_d_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_e_comment, :string
		add_column :habitacions, :colo_pmarcha_termo_elect_f_comment, :string
		add_column :habitacions, :colo_pmarcha_calde_atmos_comment, :string
		add_column :habitacions, :colo_pmarcha_calde_bajo_nox_comment, :string
		add_column :habitacions, :colo_pmarcha_calde_estanca_comment, :string
		add_column :habitacions, :techo_pintar_comment, :string
		add_column :habitacions, :techo_tipo_pintura_comment, :string
		add_column :habitacions, :techo_alisar_comment, :string
		add_column :habitacions, :techo_reparar_humedad_comment, :string
		add_column :habitacions, :pared_empapelar_comment, :string
		add_column :habitacions, :pared_quitar_papel_comment, :string
		add_column :habitacions, :pared_alisar_comment, :string
		add_column :habitacions, :pared_pintar_comment, :string
		add_column :habitacions, :pared_reparar_humedad_comment, :string
		add_column :habitacions, :carpin_friso_comment, :string
		add_column :habitacions, :puerta_colocar_comment, :string
		add_column :habitacions, :puerta_tipo_comment, :string
		add_column :habitacions, :puerta_cambio_precerco_comment, :string
		add_column :habitacions, :ventana_colocar_comment, :string
		add_column :habitacions, :ventana_tipo_comment, :string
		add_column :habitacions, :ventana_contraventana_comment, :string  	
  end
end
